version: "3"

services:
  mongo:
    image: mongo:latest
    hostname: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  nodeosd:
    image: blockchain101/eos:dawn3.0
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir --mongodb-uri mongodb://mongo:27017/EOS
    hostname: nodeosd
    container_name: nodeosd
    links:
      - mongo
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - ./data/nodeos:/opt/eosio/bin/data-dir

  keosd:
    image: blockchain101/eos:dawn3.0
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir
    stdin_open: true
    tty: true
    hostname: keosd
    container_name: keosd
    links:
      - nodeosd
    volumes:
      - ./data/wallet:/root/eosio-wallet
      - ./data/keosd:/opt/eosio/bin/data-dir

